In [21]:
import numpy as np
import tensorflow as tf
from tensorflow import keras
from tensorflow.keras import layers
from sklearn.model_selection import train_test_split
import pandas as pd
import warnings

warnings.filterwarnings('ignore')

In [4]:

df = pd.DataFrame({
    "soil_moisture": [0.10, 0.15, 0.20, 0.25, 0.40, 0.60, 0.35, 0.18,
                      0.45, 0.05, 0.80, 0.27, 0.55, 0.70, 0.12, 0.30],
    "temperature_c": [34, 30, 26, 22, 28, 30, 19, 22,
                      35, 24, 33, 33, 21, 25, 20, 29],
    "sunlight_hours": [9, 8, 7, 4, 8, 10, 3, 10,
                       12, 5, 9, 11, 2, 6, 1, 9],
    "needs_water": [1, 1, 1, 0, 0, 0, 0, 1,
                    0, 1, 0, 1, 0, 0, 1, 1]
})

In [5]:
df

    soil_moisture  temperature_c  sunlight_hours  needs_water
0            0.10             34               9            1
1            0.15             30               8            1
2            0.20             26               7            1
3            0.25             22               4            0
4            0.40             28               8            0
5            0.60             30              10            0
6            0.35             19               3            0
7            0.18             22              10            1
8            0.45             35              12            0
9            0.05             24               5            1
10           0.80             33               9            0
11           0.27             33              11            1
12           0.55             21               2            0
13           0.70             25               6            0
14           0.12             20               1            1
15           0.30             29               9            1

In [6]:
X = df[['soil_moisture','temperature_c', 'sunlight_hours']]
y = df['needs_water']

In [7]:
X_min = X.min()
X_max = X.max()
X_normalized = (X - X_min) / (X_max - X_min + 1e-8)

In [8]:
X_normalized

    soil_moisture  temperature_c  sunlight_hours
0        0.066667         0.9375        0.727273
1        0.133333         0.6875        0.636364
2        0.200000         0.4375        0.545455
3        0.266667         0.1875        0.272727
4        0.466667         0.5625        0.636364
5        0.733333         0.6875        0.818182
6        0.400000         0.0000        0.181818
7        0.173333         0.1875        0.818182
8        0.533333         1.0000        1.000000
9        0.000000         0.3125        0.363636
10       1.000000         0.8750        0.727273
11       0.293333         0.8750        0.909091
12       0.666667         0.1250        0.090909
13       0.866667         0.3750        0.454545
14       0.093333         0.0625        0.000000
15       0.333333         0.6250        0.727273

In [9]:
X_train, X_test, y_train, y_test = train_test_split(
    X_normalized, y, test_size=0.2, random_state=42, stratify=y
)

In [15]:
X_train.shape

(12, 3)

In [22]:
model = keras.Sequential([
layers.Input(shape=(X_train.shape[1],)),
layers.Dense(8, activation='relu'),
layers.Dense(1, activation='sigmoid')
])

In [25]:
model.compile(optimizer='sgd', loss='binary_crossentropy', metrics=['accuracy']) #sgd = simple gradient descent

In [ ]:
# mini batch gradient descent
history = model.fit(
    X_train.values, y_train.values,
    validation_data=(X_test.values, y_test.values),
    epochs = 100, batch_size = 4, verbose = 1
)

# gradient descent = batch gradient descent
# model.fit(
#    X_train.values, y_train.values,
#    validation_data=(X_test.values, y_test.values),
#    epochs = 100, batch_size = len(X_train), verbose = 1
# )

# stochastic gradient descent
# model.fit(
    # X_train.values, y_train.values,
    # validation_data=(X_test.values, y_test.values),
    # epochs = 100, batch_size = 1, verbose = 1
    # )

Epoch 1/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 67ms/step - accuracy: 1.0000 - loss: 0.5736 - val_accuracy: 0.7500 - val_loss: 0.5993
Epoch 2/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 30ms/step - accuracy: 1.0000 - loss: 0.5732 - val_accuracy: 0.7500 - val_loss: 0.5984
Epoch 3/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 31ms/step - accuracy: 1.0000 - loss: 0.5723 - val_accuracy: 0.7500 - val_loss: 0.5975
Epoch 4/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 35ms/step - accuracy: 1.0000 - loss: 0.5723 - val_accuracy: 0.7500 - val_loss: 0.5966
Epoch 5/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 38ms/step - accuracy: 1.0000 - loss: 0.5699 - val_accuracy: 0.7500 - val_loss: 0.5957
Epoch 6/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 46ms/step - accuracy: 1.0000 - loss: 0.5690 - val_accuracy: 0.7500 - val_loss: 0.5948
Epoch 7/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 41ms/step - accuracy: 1.0000 - loss: 0.5688 - val_accuracy: 0.7500 - val_loss: 0.5939
Epoch 8/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 44ms/step - accuracy: 1.0000 - loss: 0.5672 - val_accuracy: 0.7500 - val_loss: 0.5930
Epoch 9/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 36ms/step - accuracy: 1.0000 - loss: 0.5667 - val_accuracy: 0.7500 - val_loss: 0.5921
Epoch 10/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 46ms/step - accuracy: 1.0000 - loss: 0.5662 - val_accuracy: 0.7500 - val_loss: 0.5912
Epoch 11/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 60ms/step - accuracy: 1.0000 - loss: 0.5654 - val_accuracy: 0.7500 - val_loss: 0.5903
Epoch 12/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 58ms/step - accuracy: 1.0000 - loss: 0.5641 - val_accuracy: 0.7500 - val_loss: 0.5895
Epoch 13/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 59ms/step - accuracy: 1.0000 - loss: 0.5634 - val_accuracy: 0.7500 - val_loss: 0.5886
Epoch 14/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 57ms/step - accuracy: 1.0000 - loss: 0.5645 - val_accuracy: 0.7500 - val_loss: 0.5877
Epoch 15/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 53ms/step - accuracy: 1.0000 - loss: 0.5615 - val_accuracy: 0.7500 - val_loss: 0.5868
Epoch 16/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 45ms/step - accuracy: 1.0000 - loss: 0.5608 - val_accuracy: 0.7500 - val_loss: 0.5860
Epoch 17/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 47ms/step - accuracy: 1.0000 - loss: 0.5590 - val_accuracy: 0.7500 - val_loss: 0.5852
Epoch 18/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 32ms/step - accuracy: 1.0000 - loss: 0.5590 - val_accuracy: 0.7500 - val_loss: 0.5844
Epoch 19/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 58ms/step - accuracy: 1.0000 - loss: 0.5573 - val_accuracy: 0.7500 - val_loss: 0.5836
Epoch 20/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 44ms/step - accuracy: 1.0000 - loss: 0.5568 - val_accuracy: 0.7500 - val_loss: 0.5829
Epoch 21/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 45ms/step - accuracy: 1.0000 - loss: 0.5565 - val_accuracy: 0.7500 - val_loss: 0.5821
Epoch 22/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 59ms/step - accuracy: 1.0000 - loss: 0.5548 - val_accuracy: 0.7500 - val_loss: 0.5813
Epoch 23/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 56ms/step - accuracy: 1.0000 - loss: 0.5544 - val_accuracy: 0.7500 - val_loss: 0.5805
Epoch 24/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 47ms/step - accuracy: 1.0000 - loss: 0.5558 - val_accuracy: 0.7500 - val_loss: 0.5797
Epoch 25/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 49ms/step - accuracy: 1.0000 - loss: 0.5519 - val_accuracy: 0.7500 - val_loss: 0.5790
Epoch 26/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 52ms/step - accuracy: 1.0000 - loss: 0.5511 - val_accuracy: 0.7500 - val_loss: 0.5783
Epoch 27/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 43ms/step - accuracy: 1.0000 - loss: 0.5515 - val_accuracy: 0.7500 - val_loss: 0.5776
Epoch 28/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 57ms/step - accuracy: 1.0000 - loss: 0.5494 - val_accuracy: 0.7500 - val_loss: 0.5768
Epoch 29/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 45ms/step - accuracy: 1.0000 - loss: 0.5486 - val_accuracy: 0.7500 - val_loss: 0.5762
Epoch 30/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 61ms/step - accuracy: 1.0000 - loss: 0.5483 - val_accuracy: 0.7500 - val_loss: 0.5755
Epoch 31/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 70ms/step - accuracy: 1.0000 - loss: 0.5501 - val_accuracy: 0.7500 - val_loss: 0.5747
Epoch 32/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 93ms/step - accuracy: 1.0000 - loss: 0.5475 - val_accuracy: 0.7500 - val_loss: 0.5740
Epoch 33/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 41ms/step - accuracy: 1.0000 - loss: 0.5462 - val_accuracy: 0.7500 - val_loss: 0.5733
Epoch 34/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 38ms/step - accuracy: 1.0000 - loss: 0.5463 - val_accuracy: 0.7500 - val_loss: 0.5727
Epoch 35/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 34ms/step - accuracy: 1.0000 - loss: 0.5440 - val_accuracy: 0.7500 - val_loss: 0.5721
Epoch 36/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 39ms/step - accuracy: 1.0000 - loss: 0.5443 - val_accuracy: 0.7500 - val_loss: 0.5714
Epoch 37/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 61ms/step - accuracy: 1.0000 - loss: 0.5433 - val_accuracy: 0.7500 - val_loss: 0.5707
Epoch 38/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 60ms/step - accuracy: 1.0000 - loss: 0.5453 - val_accuracy: 0.7500 - val_loss: 0.5700
Epoch 39/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 52ms/step - accuracy: 1.0000 - loss: 0.5417 - val_accuracy: 0.7500 - val_loss: 0.5694
Epoch 40/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 53ms/step - accuracy: 1.0000 - loss: 0.5410 - val_accuracy: 0.7500 - val_loss: 0.5687
Epoch 41/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 44ms/step - accuracy: 1.0000 - loss: 0.5400 - val_accuracy: 0.7500 - val_loss: 0.5680
Epoch 42/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 45ms/step - accuracy: 1.0000 - loss: 0.5388 - val_accuracy: 0.7500 - val_loss: 0.5673
Epoch 43/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 31ms/step - accuracy: 1.0000 - loss: 0.5383 - val_accuracy: 0.7500 - val_loss: 0.5666
Epoch 44/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 49ms/step - accuracy: 1.0000 - loss: 0.5373 - val_accuracy: 0.7500 - val_loss: 0.5660
Epoch 45/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 49ms/step - accuracy: 1.0000 - loss: 0.5374 - val_accuracy: 0.7500 - val_loss: 0.5652
Epoch 46/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 43ms/step - accuracy: 1.0000 - loss: 0.5369 - val_accuracy: 0.7500 - val_loss: 0.5646
Epoch 47/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 32ms/step - accuracy: 1.0000 - loss: 0.5355 - val_accuracy: 0.7500 - val_loss: 0.5639
Epoch 48/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 30ms/step - accuracy: 1.0000 - loss: 0.5347 - val_accuracy: 0.7500 - val_loss: 0.5633
Epoch 49/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 35ms/step - accuracy: 1.0000 - loss: 0.5348 - val_accuracy: 0.7500 - val_loss: 0.5625
Epoch 50/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 28ms/step - accuracy: 1.0000 - loss: 0.5330 - val_accuracy: 0.7500 - val_loss: 0.5619
Epoch 51/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 33ms/step - accuracy: 1.0000 - loss: 0.5324 - val_accuracy: 0.7500 - val_loss: 0.5612
Epoch 52/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 37ms/step - accuracy: 1.0000 - loss: 0.5321 - val_accuracy: 0.7500 - val_loss: 0.5605
Epoch 53/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 33ms/step - accuracy: 1.0000 - loss: 0.5309 - val_accuracy: 0.7500 - val_loss: 0.5598
Epoch 54/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 32ms/step - accuracy: 1.0000 - loss: 0.5307 - val_accuracy: 0.7500 - val_loss: 0.5591
Epoch 55/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 72ms/step - accuracy: 1.0000 - loss: 0.5297 - val_accuracy: 0.7500 - val_loss: 0.5584
Epoch 56/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 40ms/step - accuracy: 1.0000 - loss: 0.5305 - val_accuracy: 0.7500 - val_loss: 0.5577
Epoch 57/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 43ms/step - accuracy: 1.0000 - loss: 0.5279 - val_accuracy: 0.7500 - val_loss: 0.5570
Epoch 58/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 42ms/step - accuracy: 1.0000 - loss: 0.5282 - val_accuracy: 0.7500 - val_loss: 0.5564
Epoch 59/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 61ms/step - accuracy: 1.0000 - loss: 0.5270 - val_accuracy: 0.7500 - val_loss: 0.5558
Epoch 60/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 57ms/step - accuracy: 1.0000 - loss: 0.5277 - val_accuracy: 0.7500 - val_loss: 0.5551
Epoch 61/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 53ms/step - accuracy: 1.0000 - loss: 0.5250 - val_accuracy: 0.7500 - val_loss: 0.5544
Epoch 62/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 63ms/step - accuracy: 1.0000 - loss: 0.5252 - val_accuracy: 0.7500 - val_loss: 0.5537
Epoch 63/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 61ms/step - accuracy: 1.0000 - loss: 0.5242 - val_accuracy: 0.7500 - val_loss: 0.5531
Epoch 64/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 47ms/step - accuracy: 1.0000 - loss: 0.5233 - val_accuracy: 0.7500 - val_loss: 0.5524
Epoch 65/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 35ms/step - accuracy: 1.0000 - loss: 0.5218 - val_accuracy: 0.7500 - val_loss: 0.5517
Epoch 66/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 41ms/step - accuracy: 1.0000 - loss: 0.5215 - val_accuracy: 0.7500 - val_loss: 0.5510
Epoch 67/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 38ms/step - accuracy: 1.0000 - loss: 0.5211 - val_accuracy: 0.7500 - val_loss: 0.5503
Epoch 68/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 39ms/step - accuracy: 1.0000 - loss: 0.5209 - val_accuracy: 0.7500 - val_loss: 0.5496
Epoch 69/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 45ms/step - accuracy: 1.0000 - loss: 0.5194 - val_accuracy: 0.7500 - val_loss: 0.5489
Epoch 70/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 58ms/step - accuracy: 1.0000 - loss: 0.5186 - val_accuracy: 0.7500 - val_loss: 0.5482
Epoch 71/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 57ms/step - accuracy: 1.0000 - loss: 0.5185 - val_accuracy: 0.7500 - val_loss: 0.5475
Epoch 72/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 57ms/step - accuracy: 1.0000 - loss: 0.5201 - val_accuracy: 0.7500 - val_loss: 0.5468
Epoch 73/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 53ms/step - accuracy: 1.0000 - loss: 0.5164 - val_accuracy: 0.7500 - val_loss: 0.5461
Epoch 74/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 54ms/step - accuracy: 1.0000 - loss: 0.5156 - val_accuracy: 0.7500 - val_loss: 0.5455
Epoch 75/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 40ms/step - accuracy: 1.0000 - loss: 0.5154 - val_accuracy: 0.7500 - val_loss: 0.5447
Epoch 76/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 51ms/step - accuracy: 1.0000 - loss: 0.5145 - val_accuracy: 0.7500 - val_loss: 0.5441
Epoch 77/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 53ms/step - accuracy: 1.0000 - loss: 0.5135 - val_accuracy: 0.7500 - val_loss: 0.5435
Epoch 78/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 56ms/step - accuracy: 1.0000 - loss: 0.5132 - val_accuracy: 0.7500 - val_loss: 0.5427
Epoch 79/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 57ms/step - accuracy: 1.0000 - loss: 0.5122 - val_accuracy: 0.7500 - val_loss: 0.5421
Epoch 80/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 53ms/step - accuracy: 1.0000 - loss: 0.5119 - val_accuracy: 0.7500 - val_loss: 0.5415
Epoch 81/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 48ms/step - accuracy: 1.0000 - loss: 0.5104 - val_accuracy: 0.7500 - val_loss: 0.5408
Epoch 82/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 42ms/step - accuracy: 1.0000 - loss: 0.5103 - val_accuracy: 0.7500 - val_loss: 0.5401
Epoch 83/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 53ms/step - accuracy: 1.0000 - loss: 0.5091 - val_accuracy: 0.7500 - val_loss: 0.5395
Epoch 84/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 55ms/step - accuracy: 1.0000 - loss: 0.5116 - val_accuracy: 0.7500 - val_loss: 0.5388
Epoch 85/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 46ms/step - accuracy: 1.0000 - loss: 0.5081 - val_accuracy: 0.7500 - val_loss: 0.5381
Epoch 86/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 48ms/step - accuracy: 1.0000 - loss: 0.5076 - val_accuracy: 0.7500 - val_loss: 0.5374
Epoch 87/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 33ms/step - accuracy: 1.0000 - loss: 0.5065 - val_accuracy: 0.7500 - val_loss: 0.5368
Epoch 88/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 46ms/step - accuracy: 1.0000 - loss: 0.5086 - val_accuracy: 0.7500 - val_loss: 0.5363
Epoch 89/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 32ms/step - accuracy: 1.0000 - loss: 0.5052 - val_accuracy: 0.7500 - val_loss: 0.5355
Epoch 90/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 56ms/step - accuracy: 1.0000 - loss: 0.5046 - val_accuracy: 0.7500 - val_loss: 0.5347
Epoch 91/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 57ms/step - accuracy: 1.0000 - loss: 0.5034 - val_accuracy: 0.7500 - val_loss: 0.5341
Epoch 92/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 51ms/step - accuracy: 1.0000 - loss: 0.5030 - val_accuracy: 0.7500 - val_loss: 0.5335
Epoch 93/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 56ms/step - accuracy: 1.0000 - loss: 0.5036 - val_accuracy: 0.7500 - val_loss: 0.5330
Epoch 94/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 51ms/step - accuracy: 1.0000 - loss: 0.5030 - val_accuracy: 0.7500 - val_loss: 0.5323
Epoch 95/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 48ms/step - accuracy: 1.0000 - loss: 0.5013 - val_accuracy: 0.7500 - val_loss: 0.5317
Epoch 96/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 33ms/step - accuracy: 1.0000 - loss: 0.5021 - val_accuracy: 0.7500 - val_loss: 0.5309
Epoch 97/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 40ms/step - accuracy: 1.0000 - loss: 0.4997 - val_accuracy: 0.7500 - val_loss: 0.5301
Epoch 98/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 59ms/step - accuracy: 1.0000 - loss: 0.4996 - val_accuracy: 0.7500 - val_loss: 0.5295
Epoch 99/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 57ms/step - accuracy: 1.0000 - loss: 0.4977 - val_accuracy: 0.7500 - val_loss: 0.5288
Epoch 100/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 55ms/step - accuracy: 1.0000 - loss: 0.4995 - val_accuracy: 0.7500 - val_loss: 0.5281

In [ ]:
from tensorflow import optimizers